[MT] Add completion rate
PartooHub/developers-website pull request #330
Opened 2023-04-07 08:56 UTC by glictevo

2023-04-07 09:29 UTC, Anders-E approved these changes

2023-04-07 14:16 UTC, psykeron commented on rest_api/v2/paths/business/post_update.yml
> +          completion_rate:
We should not document this for the request. The document is public whereas the team's implementation of the completion rate is meant for private/internal use.

right?

2023-04-07 14:17 UTC, psykeron commented on rest_api/v2/paths/business/post_create.yml
> +            $ref: '../../components/index.yml#/schemas/BusinessCompletionRate'
We should not document this for the request. The document is public whereas the team's implementation of the completion rate is meant for private/internal use.

right?

2023-04-07 14:18 UTC, psykeron requested changes
need to address comments

2023-04-11 08:42 UTC, Anivial commented on rest_api/v2/paths/business/post_create.yml
> +            $ref: '../../components/index.yml#/schemas/BusinessCompletionRate'
btw it should not be in the business POST, but business search/get only.
i'll fix it

2023-04-11 08:44 UTC, Anivial commented on rest_api/v2/paths/business/post_update.yml
> +          completion_rate:
It should be only available in business get/search, and not in business create/update, you are right.
I'll fix this

2023-04-11 09:04 UTC, psykeron approved these changes
🎸

2023-04-11 09:43 UTC, merged