[MT-1443] - Document_Attributes_endpoints for Org Admin
PartooHub/developers-website pull request #86
Opened 2020-11-26 13:31 UTC by ewalid

WHY

See email sent in comments - by provider Editus

WHAT

AS an API User, WHEN I go to the API doc, I see GET request on attribute endpoint is documented so that I can use it in my own app

2020-11-26 14:56 UTC, ClotildeAmar requested changes

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/tags/index.yml
> +    <p>They indicate things like Payment Options, Amenities, Accessibility, and Highlights.
```suggestion
    <p>They indicate things like Payment Options, Amenities, Accessibility and Highlights.
```

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +      enum: ['fr', 'es', 'it', 'en', 'de', 'pt', 'pt-BR']
bien, mais ça n'apparaît pas :/

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: Language in which the attributes will be be fetched
Plutot un truc comme : Langue dans laquelle les noms d'attributs et de groupes seront traduits
Pour ne pas donner l'impression que les attributs peuvent être différents en fonction de la langue

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: Country for which available attributes will be fetched - use ISO 3166 alpha2 code (i.e. use “FR” for France)
une liste d'exemples pour les pays chez qui on a beaucoup de clients, plutot que l'exemple dans la description

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: List of Google Attributes
```suggestion
    description: List of Google Groups
```
et peut-être une petite phrase pour expliquer ce que sont les groupes

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +        description: List of Google Attributes by Group
```suggestion
        description: List of Google Attributes
```

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +      type: string
le type affiché est "any"

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: Country for which available attributes will be fetched - use ISO 3166 alpha2 code (i.e. use “FR” for France)
Ajouter que s'il n'est pas rempli, les attributs communs à toutes les langues seront retournés

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: Google mu Business Id of the attribute
```suggestion
    description: Google my Business Id of the attribute
```
😄

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +    description: Name of the attribute
in the choosen language

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/paths/business/get_attributes.yml
> +  - $ref: '../../components/index.yml#/parameters/business_id'
Comme paramètres optionnels, il y a "category_name" et "country"

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +            properties:
J'ai juste object qui s'affiche

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +            item:
j'ai juste array qui s'affiche

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/paths/business/post_attributes.yml
> +            id:
```suggestion
            status:
```

2020-11-26 14:56 UTC, ClotildeAmar commented on rest_api/v2/paths/business/post_attributes.yml
> +  This endpoint allows you to set **Google attributes** for your business as an **ORG_ADMIN**
Tous les endpoints sont accessibles par des business_managers

2020-11-27 11:16 UTC, ewalid commented on rest_api/v2/components/index.yml
> +            properties:
![image](https://user-images.githubusercontent.com/46669517/100443647-5eeb8900-30aa-11eb-88fc-16d15164f4cd.png)

2020-11-27 12:40 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +      <p>Country for which available attributes will be fetched - use ISO 3166 alpha2 code ("FR", "EN", "IT").
pas possible de les mettre en exemple ?

2020-11-27 12:40 UTC, ClotildeAmar commented on rest_api/v2/components/index.yml
> +            properties:
j'avais pas cliqué sur la flèche :/ sorry

2020-11-27 14:04 UTC, ClotildeAmar approved these changes

2020-11-27 14:06 UTC, merged