[RT-1956] Rework reviews analytics doc
PartooHub/developers-website pull request #95
Opened 2020-12-15 17:03 UTC by rretureau

Rework the reviews analytics doc 

As a Lead Developer/Product Manager when I check all the reviews analytics APIs I see that all filters and all fields are fully and correctly described. Nothing should be missed out.

2020-12-16 17:39 UTC, huangalexpartoo reviewed
I think by looking at the example in the doc, it's not very clear what we get as a result of the request. I propose to put more than one item in the example, to feel that you will receive an array of stats where each stat corresponds to a certain date and period.

2020-12-18 13:35 UTC, huangalexpartoo approved these changes

2020-12-21 08:26 UTC, endeav reviewed
PM analytics doesn't not exactly follow the same patterns as the other APIs.
There's usually a main description in the beginning of the section that gives the context of this set of APIs, then each API can have one or 2 words to describe it's purpose and then the fields are explained in the the "Query parameters" area

2020-12-21 08:26 UTC, endeav commented on rest_api/v2/paths/reviews_analytics/get_stats.yml
> +  **Presence Management**.
RM

2020-12-21 08:26 UTC, endeav commented on rest_api/v2/paths/reviews_analytics/get_stats.yml
> +    - by keywords
All this needs to go directly at the field level

2020-12-21 08:26 UTC, endeav commented on rest_api/v2/paths/reviews_analytics/get_qualitative_evolution.yml
> +
Redundant information, they are all described further down

2020-12-21 08:26 UTC, endeav commented on rest_api/v2/components/index.yml
> +      Filter by `partner`
No quotes needed
```suggestion
      Filter by partner
```

2020-12-21 08:26 UTC, endeav commented on rest_api/v2/components/index.yml
> +  query_review_partner:
The analytics are taken into account only for Google, they cannot filter by partner.
I see there are some leftovers here in the project that we'll need to clarify.
Because we do show totals (in the stats and number of reviews graph) but the avergaes are calculated only for Google since FB doesn't have a number (just recommanded/not-recommanded) 
Could you please check this with Sofiane?
<img width="1105" alt="Screenshot 2020-12-21 at 09 24 37" src="https://user-images.githubusercontent.com/7684092/102755309-7e569880-436e-11eb-996f-6443f03c0a51.png">

2020-12-21 08:29 UTC, endeav requested changes
We actually need to fix my comments before merging this :/

2020-12-21 12:58 UTC, Exifers requested changes

2020-12-21 12:58 UTC, Exifers commented on rest_api/v2/components/index.yml
> +      For example : `update_date__gte=2019-01-01T00:00:00` will returns all reviews from the first january of 2019
```suggestion
      For example : `update_date__gte=2019-01-01T00:00:00` will return all reviews from the first January of 2019
```

2020-12-21 12:58 UTC, Exifers commented on rest_api/v2/components/index.yml
> +      cumulative sum of the number of reviews for each day.
```suggestion
      This will determine the precision of the returned data. For example, if you choose `day`, you will receive the 
      number of reviews for each day.
```

2020-12-21 12:58 UTC, Exifers commented on rest_api/v2/components/index.yml
> +      For example : `update_date__lte=2020-01-01T00:00:00` will returns all reviews from the date of the first review
```suggestion
      For example : `update_date__lte=2020-01-01T00:00:00` will return all reviews from the date of the first review
```

2020-12-21 13:01 UTC, Exifers commented on rest_api/v2/paths/reviews_analytics/get_stats.yml
> +    - by keywords
This pattern is used in [presence analytics](https://developers.partoo.co/rest_api/v2/#operation/getPresenceAnalytics), maybe we'll keep it for now and decide later if we want to remove all of them or not.

2020-12-21 13:44 UTC, Exifers approved these changes

2021-01-08 09:10 UTC, endeav approved these changes

2021-01-08 09:11 UTC, merged